### PR TITLE
experimental files for n-pentane and NOx IDTs, RCM

### PR DESCRIPTION
**Pull request by mefuller**
As seen on TV: https://doi.org/10.26434/chemrxiv.13720105 (preprint)
RCM IDTs for n-pentane doped with NO or NO2, Pc=15 bar, 650-1000 K
(50% n-pentane + NOx in air) + 50% diluent

### CODE REVIEW

**Comment by bryanwweber** [comment]
Looks great, thanks @mefuller. I think we just need to wait for a DOI for the paper and it's good to go

**Comment by mefuller** [comment]
Ok, that's fine.
My initial thought was to reference the preprint and then update later when the published version is available.

I'll update the branch once the "real" DOI is assigned

**Comment by bryanwweber** [comment]
If you put the preprint on arXiv or a similar thing with a permanent identifier, that'd be fine too.

**Comment by mefuller** [comment]
All fixed - should be ok

**Comment by mefuller** [comment]
one other thought - do the SMILES codes need to be enclosed in quotes for proper processing, e.g. [Ar] needs to be "[Ar]" to avoid reading it in as a list?

**Comment by bryanwweber** [comment]
Yes, I believe they do. Your also can't have any blank keys, just the word followed by a colon and then the next line at the same indentation.

**Comment by mefuller** [comment]
Ok, I'll get that all fixed up and push a corrected set of files.

Next time should be better

Is there already a wiki page re #4? If yes, apologies and, if not, I'll try to put what I've learned from the corrections into it

**Comment by bryanwweber** [comment]
There is not, feel free to add one, or suggest some text in that issue

**Comment by mefuller** [comment]
I think this is now good to go and I wrote in some functionality for me to update the DOI/article information in the future if desired

**Comment by mefuller** [comment]
There's a systematic error affecting some of these files (just discovered) - closing for now and will submit a new PR when ready

**Pull request closed without merging**
