### PR TITLE
Add methyl pentanoate data

### PR DESCRIPTION
**Pull request by bryanwweber**
Weber, Bryan W., Justin A. Bunnell, Kamal Kumar, and Chih-Jen Sung.
"Experiments and Modeling of the Autoignition of Methyl Pentanoate at
Low to Intermediate Temperatures and Elevated Pressures in a Rapid
Compression Machine." Fuel 212 (January 2018): 479-486.
https://doi.org/10.1016/j.fuel.2017.10.037.

### CODE REVIEW

**Comment by kyleniemeyer** [comment]
Awesome!!

I do have a few comments, not necessarily things that need changing, but for discussion:

- My preference is to have the volume time history (and in the future whatever time histories) at the end of the datapoint, so that the other stuff is more easily read. Not a big deal, and probably not worth changing, but just a thought.
- At this point we might want to start figuring out how files should be structured in the database. You have these organized by fuel / equivalence ratio / pressure; I'm fine with something like this, but if this is how we choose to organize the database, we might want to reorg the existing files to match this structure.

**Comment by kyleniemeyer** [comment]
Also, do we want a CHANGELOG for the database?

**Comment by rwest** [comment]
Regarding the changelog: isn't that why it's in git?

**Comment by kyleniemeyer** [comment]
Sure, but software projects usually have CHANGELOG files to describe the overall changes between versions etc., which have much less granular descriptions than git commit messages (e.g., you would likely use many commits to add a new big feature, but only one entry in the change log). 

But, it’s not clear to me whether we want one or not for the database.

**Comment by bryanwweber** [comment]
- Unfortunately, with the Python YAML libraries (ruamel or pyyaml), you don't have much control over the output order of the keys IIRC
- I think we need to decide on permanent identifiers for the files as well. It's also not clear how to handle multiple authors (with data for the same fuel) or what the filenames should be.
- I don't think it's necessary to add a CHANGELOG file. I don't really see what information that would add that commit logs wouldn't, since most data files should be added in a single commit I think
- We should, however, add a contributing guide and community guidelines I think
- We also need to define how we want people to reference the database. I'm not sure if making formal releases, having people cite git hashes, or what, but that will determine (in part) the best way to organize and name the files

**Comment by rwest** [comment]
I forget which yaml library, but I once hacked one to use OrderedDict instead of dict - was pretty straightforward but would mean you had a custom version to worry about (if that's a worry)

**Comment by kyleniemeyer** [comment]
I'm not that worried about the order, although I thought by default the keys came out alphabetically.

We can have a discussion about permanent identifiers in a separate issue dedicated to that—I'll open one up. I think this PR is fine to merge as-is, though, and then later we can revise the database with the permanent IDs.

Regarding the CHANGELOG, my main motivation there was to differentiate different releases of the database, since each will have a version "number" and unique DOI. The CHANGELOG would make it easier to differentiate the releases, in my opinion. This is related to @bryanwweber's last point; I *don't* want people to cite git hashes, but regular releases that have associated DOIs. 

I'll open up issues about the contributing guide and guidelines.

**Comment by bryanwweber** [comment]
I thought so too, but apparently not.

See #7

See #9

See #8 

If this is good to merge, please feel free :smiley:

**Pull request merged**
